[package]
name = "image-undump"
version = "0.0.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
image = "0.23.4"
glob = "0.3"

[dependencies.tokio]
version = "0.2"
features = ["blocking", "fs", "io-util", "rt-util", "stream"]
